In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array(1)
a

array(1)

In [6]:
a.ndim #n numberdan geliyo d = dimesnsion

0

In [9]:
b = np.array([1])
b   #b vektördür

array([1])

In [10]:
b.ndim

1

In [15]:
c = np.array([[1]])
c    #c matrisdir

array([[1]])

In [16]:
c.ndim

2

In [17]:
d = np.array([[[1]]])
d

array([[[1]]])

In [18]:
d.ndim

3

In [22]:
matris = np.array([[1],[2],[3]])
pd.DataFrame(data = matris)

0
0  1
1  2
2  3

In [24]:
np.array([[1,'ahmet',5000],[2,'buse',7000],[3,'caner',9000]])

array([['1', 'ahmet', '5000'],
       ['2', 'buse', '7000'],
       ['3', 'caner', '9000']], dtype='<U11')

In [25]:
veri = np.array([[1,'ahmet',5000],[2,'buse',7000],[3,'caner',9000]])

In [28]:
tablo = pd.DataFrame(data = veri)
tablo

0      1     2
0  1  ahmet  5000
1  2   buse  7000
2  3  caner  9000

In [29]:
idx = ["tekniker","muhendis","yuksek muhendis"]
col = ['sira','isim','maas']

In [32]:
tablo.index = idx
tablo.columns = col
tablo

sira   isim  maas
tekniker           1  ahmet  5000
muhendis           2   buse  7000
yuksek muhendis    3  caner  9000